//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyManagerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apply_temp_sync
    {
        public int ID { get; set; }
        public int userID { get; set; }
        public System.DateTime applyDate { get; set; }
        public string keepType { get; set; }
        public int flowTypeID { get; set; }
        public string flowTypeName { get; set; }
        public string InOutType { get; set; }
        public int FeeItemID { get; set; }
        public string FeeItemName { get; set; }
        public decimal imoney { get; set; }
        public int InUserBankID { get; set; }
        public int OutUserBankID { get; set; }
        public string CAdd { get; set; }
        public string applyGUID { get; set; }
        public System.DateTime applyGUIDDate { get; set; }
    }
}
