//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyManagerWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FamilyCaiWuDBEntities : DbContext
    {
        public FamilyCaiWuDBEntities()
            : base("name=FamilyCaiWuDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Apply_Main> Apply_Main { get; set; }
        public DbSet<Apply_Sub> Apply_Sub { get; set; }
        public DbSet<Apply_Sub_CashChange> Apply_Sub_CashChange { get; set; }
        public DbSet<Apply_Sub_JieKuan> Apply_Sub_JieKuan { get; set; }
        public DbSet<Bank> Banks { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<SysModel> SysModels { get; set; }
        public DbSet<UserAccount> UserAccounts { get; set; }
        public DbSet<UserBank> UserBanks { get; set; }
        public DbSet<UserModelPower> UserModelPowers { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<apply_temp_sync> apply_temp_sync { get; set; }
    }
}
